SUBSTITUTES_LIBRARY = 'data/substitutes_library.json'
SUBSTITUTES_TXT_LIBRARY = 'data/substitute.txt'
PROJECT_DIR = '.'
DATA_DIR = 'data'
NEG_PROMPTS_LIBRARY = 'data/prompts-negative-filtered.txt'
NEG_PROMPTS_LIBRARY_V2 = 'data/prompts-negative-filtered-v2.txt'
MODEL_CACHE_DIR = 'models/'